---
- name: Deploy Info Page on all servers
  hosts: all
  become: yes
  vars:
     user_name: meghana

  tasks:
  - name: Copy Dynamic Page
    template: 
      src: info.j2
      dest: /var/www/html/dynamic.html
     
...